version: '3.5'

services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - GATEWAY_URI=${GATEWAY_URI}
      - RAILS_ENV=${RAILS_ENV}
    volumes:
      - .:/go-feed:z
    ports:
      - "80:3000"
    depends_on:
      - db
    networks:
      default:
      go-feed:

  db:
    image: postgres:10.5
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:

networks:
  go-feed:
    name: go-feed
