default: &default
  adapter: postgresql
  host: <%= ENV.fetch("DATABASE_HOST") { "127.0.0.1" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>

development:
  <<: *default
  database: go-feed_development

test:
  <<: *default
  database: go-feed_test

production:
  <<: *default
  database: go-feed_production
